logging:
  level: INFO
  loggers:
    com.hummingbird: DEBUG
  appenders:
    - type: console

server:
    applicationConnectors:
      - type: http
        port: 8180
    adminConnectors:
      - type: http
        port: 8181

swagger:
  resourcePackage: com.usanin.andrew
  title: hedgehog-project


database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/hedgehog

liqui:
  baseUrl: "http://api.liqui.io/api/3/"
  httpClient:
      timeout: 35000ms
      connectionTimeout: 35000ms
      gzipEnabled: false
      gzipEnabledForRequests: false
      chunkedEncodingEnabled: false